// script.js

const cursos = [
  // Ciclo 1
  { nombre: "Globalización y Realidad Nacional", ciclo: 1 },
  { nombre: "Lenguaje y Comunicación I", ciclo: 1 },
  { nombre: "Ética Cívica", ciclo: 1 },
  { nombre: "Metodología de Investigación", ciclo: 1 },
  { nombre: "Desarrollo y Personal Social", ciclo: 1 },
  { nombre: "Matemática Básica", ciclo: 1 },
  // Ciclo 2
  { nombre: "Economía y Empresa", ciclo: 2 },
  { nombre: "Lenguaje y Comunicación II", ciclo: 2 },
  { nombre: "Estadística Básica para los Negocios", ciclo: 2 },
  { nombre: "Procesos Sociales y Políticos", ciclo: 2 },
  { nombre: "Temas de Filosofía", ciclo: 2 },
  { nombre: "Matemática Aplicada a los Negocios", ciclo: 2 },
  // Ciclo 3
  { nombre: "Introduction to International Business", ciclo: 3, prerequisitos: ["Economía y Empresa"] },
  { nombre: "Estadística para la Gestión Empresarial I", ciclo: 3, prerequisitos: ["Estadística Básica para los Negocios"] },
  { nombre: "Relaciones Internacionales / International Relations", ciclo: 3, prerequisitos: ["Procesos Sociales y Políticos"] },
  { nombre: "Cross-Cultural in Business", ciclo: 3, prerequisitos: ["Procesos Sociales y Políticos"] },
  { nombre: "Matemática para la Gestión de Negocios", ciclo: 3, prerequisitos: ["Matemática Aplicada a los Negocios"] },
  { nombre: "Contabilidad General", ciclo: 3, prerequisitos: ["Matemática Aplicada a los Negocios"] },
  // Ciclo 4
  { nombre: "Regulation of International Business Transactions", ciclo: 4, prerequisitos: ["Introduction to International Business"] },
  { nombre: "Microeconomía / Microeconomics", ciclo: 4, prerequisitos: ["Introduction to International Business"] },
  { nombre: "International Business Workshop I", ciclo: 4, prerequisitos: ["Lenguaje y Comunicación II"] },
  { nombre: "Estadística para la Gestión Empresarial II", ciclo: 4, prerequisitos: ["Estadística para la Gestión Empresarial I"] },
  { nombre: "Marketing Internacional, Estudio de Mercado y Estrategias de Venta / International Marketing, Market Research and Sales Strategies", ciclo: 4, prerequisitos: ["Estadística para la Gestión Empresarial I"] },
  { nombre: "Economic Integration Processes", ciclo: 4, prerequisitos: ["Relaciones Internacionales / International Relations"] },
  { nombre: "Costos y Presupuestos", ciclo: 4, prerequisitos: ["Contabilidad General"] },
  // Ciclo 5
  { nombre: "Exports, Imports and Customs", ciclo: 5, prerequisitos: ["Regulation of International Business Transactions"] },
  { nombre: "Macroeconomía / Macroenomics", ciclo: 5, prerequisitos: ["Microeconomía / Microeconomics"] },
  { nombre: "International Business Workshop II", ciclo: 5, prerequisitos: ["Introduction to International Business"] },
  { nombre: "Métodos Cuantitativos para la Investigación en Negocios Internacionales", ciclo: 5, prerequisitos: ["Estadística para la Gestión Empresarial II"] },
  { nombre: "Inteligencia en los Negocios y Big Data", ciclo: 5, prerequisitos: ["Estadística para la Gestión Empresarial II", "Marketing Internacional, Estudio de Mercado y Estrategias de Venta / International Marketing, Market Research and Sales Strategies"] },
  { nombre: "Inteligencia de Mercados Internacionales/ International Market Intelligence", ciclo: 5, prerequisitos: ["Marketing Internacional, Estudio de Mercado y Estrategias de Venta / International Marketing, Market Research and Sales Strategies"] },
  { nombre: "Emprendimiento de Negocios Globales y Digitales", ciclo: 5, prerequisitos: ["Marketing Internacional, Estudio de Mercado y Estrategias de Venta / International Marketing, Market Research and Sales Strategies"] },
  // Ciclo 6
  { nombre: "International Logístics I", ciclo: 6, prerequisitos: ["Exports, Imports and Customs"] },
  { nombre: "Development and Innovation of International Services", ciclo: 6, prerequisitos: ["Macroeconomía / Macroenomics"] },
  { nombre: "Teoría del Comercio Internacional / Theory of International Trade", ciclo: 6, prerequisitos: ["Macroeconomía / Macroenomics"] },
  { nombre: "International Business Strategies and Sustainability", ciclo: 6, prerequisitos: ["Macroeconomía / Macroenomics"] },
  { nombre: "Data Analytics Aplicados a los Negocios Internacionales", ciclo: 6, prerequisitos: ["Inteligencia en los Negocios y Big Data"] },
  { nombre: "Comportamiento de Mercados Internacionales", ciclo: 6, prerequisitos: ["Inteligencia de Mercados Internacionales/ International Market Intelligence"] },
  { nombre: "Taller de Inteligencia de Mercados Internacionales", ciclo: 6, prerequisitos: ["Inteligencia de Mercados Internacionales/ International Market Intelligence"] },
  { nombre: "Cooperación Internacional para el Desarrollo Sostenible", ciclo: 6, prerequisitos: ["Economic Integration Processes"] },
  { nombre: "Finanzas Empresariales I", ciclo: 6, prerequisitos: ["Matemática para la Gestión de Negocios"] },
  // Ciclo 7
  { nombre: "International Logistics II", ciclo: 7, prerequisitos: ["International Logístics I"] },
  { nombre: "Taller de Liderazgo y Habilidades Gerenciales", ciclo: 7, prerequisitos: ["Teoría del Comercio Internacional / Theory of International Trade"] },
  { nombre: "Global Standards Requirements", ciclo: 7, prerequisitos: ["Development and Innovation of International Services", "International Business Strategies and Sustainability"] },
  { nombre: "Estrategias de Producción y Precios Internacionales / Production Strategies and International Price", ciclo: 7, prerequisitos: ["International Business Strategies and Sustainability"] },
  { nombre: "Innovation and International Product Development", ciclo: 7, prerequisitos: ["Comportamiento de Mercados Internacionales"] },
  { nombre: "Estrategias Aplicadas para la Negociación Internacional / Applied Strategies to International Negotiation", ciclo: 7, prerequisitos: ["Cross-Cultural in Business", "Economic Integration Processes"] },
  { nombre: "Finanzas Empresariales II", ciclo: 7, prerequisitos: ["Finanzas Empresariales I"] },
  // Ciclo 8
  { nombre: "Global Supply Chain Management", ciclo: 8, prerequisitos: ["International Logistics II"] },
  { nombre: "Gestión de Operaciones Globales I", ciclo: 8, prerequisitos: ["International Logistics II"] },
  { nombre: "Etica y Sostenibilidad Empresarial / Ethics and Business Sustainability", ciclo: 8, prerequisitos: ["Teoría del Comercio Internacional / Theory of International Trade"] },
  { nombre: "Circularidad en Negocios Internacionales", ciclo: 8, prerequisitos: ["Global Standards Requirements"] },
  { nombre: "Taller Textil y Confecciones", ciclo: 8, prerequisitos: ["Estrategias de Producción y Precios Internacionales / Production Strategies and International Price"] },
  { nombre: "Taller de Minería e Hidrocarburos", ciclo: 8, prerequisitos: ["Estrategias de Producción y Precios Internacionales / Production Strategies and International Price"] },
  { nombre: "Seminario Integrador de Negocios Internacionales / International Business Research", ciclo: 8, prerequisitos: ["Métodos Cuantitativos para la Investigación en Negocios Internacionales", "Estrategias de Producción y Precios Internacionales / Production Strategies and International Price"] },
  { nombre: "Commercial Promotion, Sales and International Comunication", ciclo: 8, prerequisitos: ["Innovation and International Product Development"] },
  { nombre: "Innovación y Diseño de Productos Internacionales / Innovation and International Product Design", ciclo: 8, prerequisitos: ["Innovation and International Product Development"] },
  { nombre: "Diplomacia y Protocolo/ Diplomacy and Protocol", ciclo: 8, prerequisitos: ["Economic Integration Processes"] },
  { nombre: "Doing Global Business and Foreign Direct Investment", ciclo: 8, prerequisitos: ["Estrategias Aplicadas para la Negociación Internacional / Applied Strategies to International Negotiation"] },
  { nombre: "Global Leadership", ciclo: 8, prerequisitos: ["Estrategias Aplicadas para la Negociación Internacional / Applied Strategies to International Negotiation"] },
  { nombre: "International Trade Finance I", ciclo: 8, prerequisitos: ["Finanzas Empresariales II"] },
  { nombre: "Mercado de Valores / Stock Market", ciclo: 8, prerequisitos: ["Finanzas Empresariales II"] },
  // Ciclo 9
  { nombre: "Taller de Logistica Internacional", ciclo: 9, prerequisitos: ["Global Supply Chain Management"] },
  { nombre: "Global Human Resources", ciclo: 9, prerequisitos: ["Etica y Sostenibilidad Empresarial / Ethics and Business Sustainability"] },
  { nombre: "Strategic Alliances", ciclo: 9, prerequisitos: ["Global Standards Requirements"] },
  { nombre: "Taller de Agronegocios", ciclo: 9, prerequisitos: ["Estrategias de Producción y Precios Internacionales / Production Strategies and International Price"] },
  { nombre: "Taller de Pesca y Acuicultura", ciclo: 9, prerequisitos: ["Estrategias de Producción y Precios Internacionales / Production Strategies and International Price"] },
  { nombre: "Seminario de Investigación en Negocios Internacionales I / International Business Research I", ciclo: 9, prerequisitos: ["Seminario Integrador de Negocios Internacionales / International Business Research"] },
  { nombre: "Desarrollo de Proyectos Sostenibles Internacionales / Development of International Sustainable Projects", ciclo: 9, prerequisitos: ["Commercial Promotion, Sales and International Comunication"] },
  { nombre: "Oportunidades de Importación y Exportación", ciclo: 9, prerequisitos: ["Commercial Promotion, Sales and International Comunication"] },
  { nombre: "Política de Comercio Exterior Comparada", ciclo: 9, prerequisitos: ["Doing Global Business and Foreign Direct Investment"] },
  { nombre: "International Trade Finance II", ciclo: 9, prerequisitos: ["International Trade Finance I"] },
  { nombre: "Evaluación Financiera de Proyectos de Inversión", ciclo: 9, prerequisitos: ["International Trade Finance I"] },
  { nombre: "Advance International Finance", ciclo: 9, prerequisitos: ["International Trade Finance I"] },
  // Ciclo 10
  { nombre: "Global Logistics Management", ciclo: 10, prerequisitos: ["Global Supply Chain Management"] },
  { nombre: "Gestión de Operaciones Globales II", ciclo: 10, prerequisitos: ["Global Supply Chain Management"] },
  { nombre: "Dirección Estratégica Internacional / International Strategic Management", ciclo: 10, prerequisitos: ["Strategic Alliances"] },
  { nombre: "Seminario de Investigación en Negocios Internacionales II / International Business Research II", ciclo: 10, prerequisitos: ["Seminario de Investigación en Negocios Internacionales I / International Business Research I"] },
  { nombre: "Integración Económica Comercial Asia Pacífico", ciclo: 10, prerequisitos: ["Doing Global Business and Foreign Direct Investment"] },
  { nombre: "International Corporate Finance", ciclo: 10, prerequisitos: ["International Trade Finance II"] },
  { nombre: "Gestión del Riesgo en Proyectos Internacionales", ciclo: 10, prerequisitos: ["International Trade Finance I"] }
];
